name: Deploy Go Web App -Sambar Registrace

on:
  push:
    branches:
      - main # Change this to the branch you want to deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Stop Web App Service
      #   run: |
      #     Stop-Service -Name "sambar-wall-web-app"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build Go Web App
        run: |
          go build -v -o tmp/sambar-wall-web-app.exe -ldflags "-s -w"

      - name: Deploy Content
        run: |
          # Add your deployment script or commands here
          # For example, if you just need to copy files to a destination
          cp -r static C:\inetpub\wwwroot\sambar-registrace
          cp tmp/sambar-wall-web-app.exe C:\inetpub\wwwroot\sambar-registrace
